# Generated by Django 6.0.3 on 2026-03-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentrecord',
            name='signature_image',
            field=models.TextField(blank=True, default=''),
        ),
    ]
