# Generated by Django 6.0.3 on 2026-05-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_tenant_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='landlord_response',
            field=models.TextField(blank=True, default='', help_text='Optional statement from the landlord on this agreement (visible to tenant and admin).'),
        ),
    ]
